spring:
  application:
    name: gateway

  cloud:
    loadbalancer:
      enabled: true

    gateway:
      server:
        webflux:
          routes:
<<<<<<< HEAD
=======
            - id: habitaciones
              uri: lb://habitaciones
              predicates:
                - Path=/api/habitaciones/**
              filters:
                - StripPrefix=2

>>>>>>> d0d11b5 (CRUD actualización)
            - id: huesped
              uri: lb://huesped
              predicates:
                - Path=/api/huesped/**
              filters:
                - StripPrefix=2

            - id: usuarios
              uri: lb://usuarios
              predicates:
                - Path=/api/usuarios/**
              filters:
                - StripPrefix=2

            - id: reservasHoteleras
              uri: lb://reservasHoteleras
              predicates:
                - Path=/api/reservaciones/**
              filters:
                - StripPrefix=2

            - id: habitaciones
              uri: lb://habitaciones
              predicates:
                - Path=/api/habitaciones/**
              filters:
                - StripPrefix=2

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true